# Generated by Django 2.2.1 on 2019-05-27 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0005_auto_20190527_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_info',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myAPP.login_info'),
        ),
    ]
