# Generated by Django 2.2.1 on 2019-05-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0006_auto_20190527_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_info',
            name='age',
            field=models.IntegerField(default=31),
            preserve_default=False,
        ),
    ]
