# Generated by Django 2.2.1 on 2019-05-30 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0007_patient_info_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='symptom_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F', 'Familial'), ('E', 'Early-onset'), ('L', 'Late-onset')], max_length=1)),
                ('symptom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='myAPP.login_info')),
            ],
        ),
    ]
