# Generated by Django 2.2.1 on 2019-06-09 05:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0009_remove_patient_info_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='moca_info',
            fields=[
                ('mocaID', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('version', models.CharField(max_length=10)),
                ('question_1_1', models.TextField()),
                ('question_1_2', models.TextField()),
                ('question_1_3', models.TextField()),
                ('question_2_1', models.CharField(max_length=20)),
                ('question_2_2', models.CharField(max_length=20)),
                ('question_2_3', models.CharField(max_length=20)),
                ('question_3_1', models.BinaryField()),
                ('question_4_1', models.BinaryField()),
                ('question_4_2', models.BinaryField()),
                ('question_4_3', models.CharField(max_length=50)),
                ('question_4_4', models.CharField(max_length=20)),
                ('question_5_1', models.BinaryField()),
                ('question_5_2', models.BinaryField()),
                ('question_5_3', models.BinaryField()),
                ('question_6_1', models.CharField(max_length=100)),
                ('question_3_2_1', models.CharField(max_length=100)),
                ('question_3_2_2', models.BinaryField()),
                ('question_7_1', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user3', to='myAPP.login_info')),
            ],
        ),
    ]
