# Generated by Django 2.2.1 on 2019-06-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0010_moca_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moca_info',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
