# Generated by Django 2.2.1 on 2019-06-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0011_auto_20190609_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moca_info',
            name='question_3_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moca_info',
            name='question_3_2_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moca_info',
            name='question_4_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moca_info',
            name='question_4_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moca_info',
            name='question_5_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moca_info',
            name='question_5_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moca_info',
            name='question_5_3',
            field=models.TextField(),
        ),
    ]
