# Generated by Django 2.2.1 on 2019-10-12 05:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0012_auto_20190609_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_info',
            fields=[
                ('userID', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
